name: Build

on:
  push:
    branches: '**'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
      - name: build
        run: |
          make build
      - name: lint
        uses: golangci/golangci-lint-action@v8
