name: Build

on:
  push:
    branches: '**'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
      - name: dependencies
        run: |
          sudo apt-get install libbtrfs-dev -y
      - name: build
        run: |
          make build
      - name: lint
        run: |
          make lint-dependencies
          make lint
