name: Lint

on:
  push:
    branches: '**'

permissions:
  contents: write

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v8
