name: Release

on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
      - name: release
        run: |
          make build
          make release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
