name: Sec

on:
  push:
    branches: '**'

permissions:
  contents: write

jobs:
  sec:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
      - name: dependencies
        run: |
          apt-get install libbtrfs-dev -y
      - name: govulncheck
        uses: golang/govulncheck-action@v1
        with:
           go-package: ./...
      - name: trivy
        uses: aquasecurity/trivy-action@0.28.0
        with:
          scan-type: 'fs'
          scan-ref: '.'
